/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.records;


import com.yupay.amasua.fv3800.model.enums.ListIds;
import com.yupay.amasua.fv3800.model.jooq.tables.CodeList;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeListRecord extends UpdatableRecordImpl<CodeListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>code_list.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>code_list.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>code_list.list_id</code>.
     */
    public void setListId(ListIds value) {
        set(1, value);
    }

    /**
     * Getter for <code>code_list.list_id</code>.
     */
    public ListIds getListId() {
        return (ListIds) get(1);
    }

    /**
     * Setter for <code>code_list.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>code_list.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>code_list.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>code_list.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>code_list.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>code_list.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>code_list.tax_alternate_code</code>.
     */
    public void setTaxAlternateCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>code_list.tax_alternate_code</code>.
     */
    public String getTaxAlternateCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>code_list.active</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>code_list.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeListRecord
     */
    public CodeListRecord() {
        super(CodeList.CODE_LIST);
    }

    /**
     * Create a detached, initialised CodeListRecord
     */
    public CodeListRecord(Integer id, ListIds listId, String code, String description, Integer sortOrder, String taxAlternateCode, Boolean active) {
        super(CodeList.CODE_LIST);

        setId(id);
        setListId(listId);
        setCode(code);
        setDescription(description);
        setSortOrder(sortOrder);
        setTaxAlternateCode(taxAlternateCode);
        setActive(active);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised CodeListRecord
     */
    public CodeListRecord(com.yupay.amasua.fv3800.model.jooq.tables.pojos.CodeList value) {
        super(CodeList.CODE_LIST);

        if (value != null) {
            setId(value.getId());
            setListId(value.getListId());
            setCode(value.getCode());
            setDescription(value.getDescription());
            setSortOrder(value.getSortOrder());
            setTaxAlternateCode(value.getTaxAlternateCode());
            setActive(value.getActive());
            resetTouchedOnNotNull();
        }
    }
}
