/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.records;


import com.yupay.amasua.fv3800.model.jooq.tables.FilingHistory;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilingHistoryRecord extends UpdatableRecordImpl<FilingHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>filing_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>filing_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>filing_history.order_number</code>.
     */
    public void setOrderNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>filing_history.order_number</code>.
     */
    public String getOrderNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>filing_history.filed_at</code>.
     */
    public void setFiledAt(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>filing_history.filed_at</code>.
     */
    public LocalDate getFiledAt() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>filing_history.period</code>.
     */
    public void setPeriod(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>filing_history.period</code>.
     */
    public String getPeriod() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilingHistoryRecord
     */
    public FilingHistoryRecord() {
        super(FilingHistory.FILING_HISTORY);
    }

    /**
     * Create a detached, initialised FilingHistoryRecord
     */
    public FilingHistoryRecord(Integer id, String orderNumber, LocalDate filedAt, String period) {
        super(FilingHistory.FILING_HISTORY);

        setId(id);
        setOrderNumber(orderNumber);
        setFiledAt(filedAt);
        setPeriod(period);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FilingHistoryRecord
     */
    public FilingHistoryRecord(com.yupay.amasua.fv3800.model.jooq.tables.pojos.FilingHistory value) {
        super(FilingHistory.FILING_HISTORY);

        if (value != null) {
            setId(value.getId());
            setOrderNumber(value.getOrderNumber());
            setFiledAt(value.getFiledAt());
            setPeriod(value.getPeriod());
            resetTouchedOnNotNull();
        }
    }
}
