/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.records;


import com.yupay.amasua.fv3800.model.enums.EntitySubtype;
import com.yupay.amasua.fv3800.model.jooq.tables.HeaderInfo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HeaderInfoRecord extends UpdatableRecordImpl<HeaderInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>header_info.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>header_info.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>header_info.ruc</code>.
     */
    public void setRuc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>header_info.ruc</code>.
     */
    public String getRuc() {
        return (String) get(1);
    }

    /**
     * Setter for <code>header_info.periodo</code>.
     */
    public void setPeriodo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>header_info.periodo</code>.
     */
    public String getPeriodo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>header_info.is_incorporated</code>.
     */
    public void setIsIncorporated(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>header_info.is_incorporated</code>.
     */
    public Boolean getIsIncorporated() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>header_info.entity_subtype</code>.
     */
    public void setEntitySubtype(EntitySubtype value) {
        set(4, value);
    }

    /**
     * Getter for <code>header_info.entity_subtype</code>.
     */
    public EntitySubtype getEntitySubtype() {
        return (EntitySubtype) get(4);
    }

    /**
     * Setter for <code>header_info.entity_subtype_name</code>.
     */
    public void setEntitySubtypeName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>header_info.entity_subtype_name</code>.
     */
    public String getEntitySubtypeName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>header_info.tin</code>.
     */
    public void setTin(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>header_info.tin</code>.
     */
    public String getTin() {
        return (String) get(6);
    }

    /**
     * Setter for <code>header_info.legal_name</code>.
     */
    public void setLegalName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>header_info.legal_name</code>.
     */
    public String getLegalName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>header_info.country</code>.
     */
    public void setCountry(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>header_info.country</code>.
     */
    public Integer getCountry() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>header_info.mobile</code>.
     */
    public void setMobile(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>header_info.mobile</code>.
     */
    public String getMobile() {
        return (String) get(9);
    }

    /**
     * Setter for <code>header_info.mail</code>.
     */
    public void setMail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>header_info.mail</code>.
     */
    public String getMail() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HeaderInfoRecord
     */
    public HeaderInfoRecord() {
        super(HeaderInfo.HEADER_INFO);
    }

    /**
     * Create a detached, initialised HeaderInfoRecord
     */
    public HeaderInfoRecord(Integer id, String ruc, String periodo, Boolean isIncorporated, EntitySubtype entitySubtype, String entitySubtypeName, String tin, String legalName, Integer country, String mobile, String mail) {
        super(HeaderInfo.HEADER_INFO);

        setId(id);
        setRuc(ruc);
        setPeriodo(periodo);
        setIsIncorporated(isIncorporated);
        setEntitySubtype(entitySubtype);
        setEntitySubtypeName(entitySubtypeName);
        setTin(tin);
        setLegalName(legalName);
        setCountry(country);
        setMobile(mobile);
        setMail(mail);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised HeaderInfoRecord
     */
    public HeaderInfoRecord(com.yupay.amasua.fv3800.model.jooq.tables.pojos.HeaderInfo value) {
        super(HeaderInfo.HEADER_INFO);

        if (value != null) {
            setId(value.getId());
            setRuc(value.getRuc());
            setPeriodo(value.getPeriodo());
            setIsIncorporated(value.getIsIncorporated());
            setEntitySubtype(value.getEntitySubtype());
            setEntitySubtypeName(value.getEntitySubtypeName());
            setTin(value.getTin());
            setLegalName(value.getLegalName());
            setCountry(value.getCountry());
            setMobile(value.getMobile());
            setMail(value.getMail());
            resetTouchedOnNotNull();
        }
    }
}
