/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.records;


import com.yupay.amasua.fv3800.model.enums.DoiType;
import com.yupay.amasua.fv3800.model.enums.IndirectType;
import com.yupay.amasua.fv3800.model.jooq.tables.Involvement;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InvolvementRecord extends UpdatableRecordImpl<InvolvementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>involvement.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>involvement.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>involvement.has_ownership</code>.
     */
    public void setHasOwnership(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>involvement.has_ownership</code>.
     */
    public Boolean getHasOwnership() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>involvement.has_control</code>.
     */
    public void setHasControl(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>involvement.has_control</code>.
     */
    public Boolean getHasControl() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>involvement.has_senior_mgmt</code>.
     */
    public void setHasSeniorMgmt(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>involvement.has_senior_mgmt</code>.
     */
    public Boolean getHasSeniorMgmt() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>involvement.is_direct</code>.
     */
    public void setIsDirect(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>involvement.is_direct</code>.
     */
    public Boolean getIsDirect() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>involvement.indirect_type</code>.
     */
    public void setIndirectType(IndirectType value) {
        set(5, value);
    }

    /**
     * Getter for <code>involvement.indirect_type</code>.
     */
    public IndirectType getIndirectType() {
        return (IndirectType) get(5);
    }

    /**
     * Setter for <code>involvement.indirect_relationship</code>.
     */
    public void setIndirectRelationship(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>involvement.indirect_relationship</code>.
     */
    public Integer getIndirectRelationship() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>involvement.titular_doi_type</code>.
     */
    public void setTitularDoiType(DoiType value) {
        set(7, value);
    }

    /**
     * Getter for <code>involvement.titular_doi_type</code>.
     */
    public DoiType getTitularDoiType() {
        return (DoiType) get(7);
    }

    /**
     * Setter for <code>involvement.titular_doi_number</code>.
     */
    public void setTitularDoiNumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>involvement.titular_doi_number</code>.
     */
    public String getTitularDoiNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>involvement.value_type</code>.
     */
    public void setValueType(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>involvement.value_type</code>.
     */
    public Integer getValueType() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>involvement.value_count</code>.
     */
    public void setValueCount(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>involvement.value_count</code>.
     */
    public BigDecimal getValueCount() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>involvement.value_nominal</code>.
     */
    public void setValueNominal(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>involvement.value_nominal</code>.
     */
    public BigDecimal getValueNominal() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>involvement.participation_percentage</code>.
     */
    public void setParticipationPercentage(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>involvement.participation_percentage</code>.
     */
    public BigDecimal getParticipationPercentage() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>involvement.has_voting_rights</code>.
     */
    public void setHasVotingRights(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>involvement.has_voting_rights</code>.
     */
    public Boolean getHasVotingRights() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>involvement.deposit_country</code>.
     */
    public void setDepositCountry(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>involvement.deposit_country</code>.
     */
    public Integer getDepositCountry() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>involvement.control_description</code>.
     */
    public void setControlDescription(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>involvement.control_description</code>.
     */
    public String getControlDescription() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvolvementRecord
     */
    public InvolvementRecord() {
        super(Involvement.INVOLVEMENT);
    }

    /**
     * Create a detached, initialised InvolvementRecord
     */
    public InvolvementRecord(Integer id, Boolean hasOwnership, Boolean hasControl, Boolean hasSeniorMgmt, Boolean isDirect, IndirectType indirectType, Integer indirectRelationship, DoiType titularDoiType, String titularDoiNumber, Integer valueType, BigDecimal valueCount, BigDecimal valueNominal, BigDecimal participationPercentage, Boolean hasVotingRights, Integer depositCountry, String controlDescription) {
        super(Involvement.INVOLVEMENT);

        setId(id);
        setHasOwnership(hasOwnership);
        setHasControl(hasControl);
        setHasSeniorMgmt(hasSeniorMgmt);
        setIsDirect(isDirect);
        setIndirectType(indirectType);
        setIndirectRelationship(indirectRelationship);
        setTitularDoiType(titularDoiType);
        setTitularDoiNumber(titularDoiNumber);
        setValueType(valueType);
        setValueCount(valueCount);
        setValueNominal(valueNominal);
        setParticipationPercentage(participationPercentage);
        setHasVotingRights(hasVotingRights);
        setDepositCountry(depositCountry);
        setControlDescription(controlDescription);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised InvolvementRecord
     */
    public InvolvementRecord(com.yupay.amasua.fv3800.model.jooq.tables.pojos.Involvement value) {
        super(Involvement.INVOLVEMENT);

        if (value != null) {
            setId(value.getId());
            setHasOwnership(value.getHasOwnership());
            setHasControl(value.getHasControl());
            setHasSeniorMgmt(value.getHasSeniorMgmt());
            setIsDirect(value.getIsDirect());
            setIndirectType(value.getIndirectType());
            setIndirectRelationship(value.getIndirectRelationship());
            setTitularDoiType(value.getTitularDoiType());
            setTitularDoiNumber(value.getTitularDoiNumber());
            setValueType(value.getValueType());
            setValueCount(value.getValueCount());
            setValueNominal(value.getValueNominal());
            setParticipationPercentage(value.getParticipationPercentage());
            setHasVotingRights(value.getHasVotingRights());
            setDepositCountry(value.getDepositCountry());
            setControlDescription(value.getControlDescription());
            resetTouchedOnNotNull();
        }
    }
}
