/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.records;


import com.yupay.amasua.fv3800.model.enums.DoiType;
import com.yupay.amasua.fv3800.model.enums.MaritalStatus;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PaykunaRecord extends UpdatableRecordImpl<PaykunaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>paykuna.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>paykuna.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>paykuna.resident</code>.
     */
    public void setResident(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>paykuna.resident</code>.
     */
    public Boolean getResident() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>paykuna.doi_type</code>.
     */
    public void setDoiType(DoiType value) {
        set(2, value);
    }

    /**
     * Getter for <code>paykuna.doi_type</code>.
     */
    public DoiType getDoiType() {
        return (DoiType) get(2);
    }

    /**
     * Setter for <code>paykuna.doi_number</code>.
     */
    public void setDoiNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>paykuna.doi_number</code>.
     */
    public String getDoiNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>paykuna.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>paykuna.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>paykuna.country_residence</code>.
     */
    public void setCountryResidence(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>paykuna.country_residence</code>.
     */
    public Integer getCountryResidence() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>paykuna.birthday</code>.
     */
    public void setBirthday(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>paykuna.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>paykuna.country_nationality</code>.
     */
    public void setCountryNationality(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>paykuna.country_nationality</code>.
     */
    public Integer getCountryNationality() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>paykuna.address</code>.
     */
    public void setAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>paykuna.address</code>.
     */
    public String getAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>paykuna.corporate_role</code>.
     */
    public void setCorporateRole(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>paykuna.corporate_role</code>.
     */
    public Integer getCorporateRole() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>paykuna.phone</code>.
     */
    public void setPhone(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>paykuna.phone</code>.
     */
    public String getPhone() {
        return (String) get(10);
    }

    /**
     * Setter for <code>paykuna.marital_status</code>.
     */
    public void setMaritalStatus(MaritalStatus value) {
        set(11, value);
    }

    /**
     * Getter for <code>paykuna.marital_status</code>.
     */
    public MaritalStatus getMaritalStatus() {
        return (MaritalStatus) get(11);
    }

    /**
     * Setter for <code>paykuna.notice_date</code>.
     */
    public void setNoticeDate(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>paykuna.notice_date</code>.
     */
    public LocalDate getNoticeDate() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>paykuna.spouse</code>.
     */
    public void setSpouse(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>paykuna.spouse</code>.
     */
    public Integer getSpouse() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>paykuna.is_legal_representative</code>.
     */
    public void setIsLegalRepresentative(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>paykuna.is_legal_representative</code>.
     */
    public Boolean getIsLegalRepresentative() {
        return (Boolean) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaykunaRecord
     */
    public PaykunaRecord() {
        super(Paykuna.PAYKUNA);
    }

    /**
     * Create a detached, initialised PaykunaRecord
     */
    public PaykunaRecord(Integer id, Boolean resident, DoiType doiType, String doiNumber, String name, Integer countryResidence, LocalDate birthday, Integer countryNationality, String address, Integer corporateRole, String phone, MaritalStatus maritalStatus, LocalDate noticeDate, Integer spouse, Boolean isLegalRepresentative) {
        super(Paykuna.PAYKUNA);

        setId(id);
        setResident(resident);
        setDoiType(doiType);
        setDoiNumber(doiNumber);
        setName(name);
        setCountryResidence(countryResidence);
        setBirthday(birthday);
        setCountryNationality(countryNationality);
        setAddress(address);
        setCorporateRole(corporateRole);
        setPhone(phone);
        setMaritalStatus(maritalStatus);
        setNoticeDate(noticeDate);
        setSpouse(spouse);
        setIsLegalRepresentative(isLegalRepresentative);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised PaykunaRecord
     */
    public PaykunaRecord(com.yupay.amasua.fv3800.model.jooq.tables.pojos.Paykuna value) {
        super(Paykuna.PAYKUNA);

        if (value != null) {
            setId(value.getId());
            setResident(value.getResident());
            setDoiType(value.getDoiType());
            setDoiNumber(value.getDoiNumber());
            setName(value.getName());
            setCountryResidence(value.getCountryResidence());
            setBirthday(value.getBirthday());
            setCountryNationality(value.getCountryNationality());
            setAddress(value.getAddress());
            setCorporateRole(value.getCorporateRole());
            setPhone(value.getPhone());
            setMaritalStatus(value.getMaritalStatus());
            setNoticeDate(value.getNoticeDate());
            setSpouse(value.getSpouse());
            setIsLegalRepresentative(value.getIsLegalRepresentative());
            resetTouchedOnNotNull();
        }
    }
}
