/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.records;


import com.yupay.amasua.fv3800.model.jooq.tables.SpouseParty;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpousePartyRecord extends UpdatableRecordImpl<SpousePartyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>spouse_party.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>spouse_party.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>spouse_party.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spouse_party.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spouse_party.doi_number</code>.
     */
    public void setDoiNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spouse_party.doi_number</code>.
     */
    public String getDoiNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spouse_party.certain_date</code>.
     */
    public void setCertainDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>spouse_party.certain_date</code>.
     */
    public LocalDate getCertainDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>spouse_party.certain_document</code>.
     */
    public void setCertainDocument(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>spouse_party.certain_document</code>.
     */
    public String getCertainDocument() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpousePartyRecord
     */
    public SpousePartyRecord() {
        super(SpouseParty.SPOUSE_PARTY);
    }

    /**
     * Create a detached, initialised SpousePartyRecord
     */
    public SpousePartyRecord(Integer id, String name, String doiNumber, LocalDate certainDate, String certainDocument) {
        super(SpouseParty.SPOUSE_PARTY);

        setId(id);
        setName(name);
        setDoiNumber(doiNumber);
        setCertainDate(certainDate);
        setCertainDocument(certainDocument);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SpousePartyRecord
     */
    public SpousePartyRecord(com.yupay.amasua.fv3800.model.jooq.tables.pojos.SpouseParty value) {
        super(SpouseParty.SPOUSE_PARTY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDoiNumber(value.getDoiNumber());
            setCertainDate(value.getCertainDate());
            setCertainDocument(value.getCertainDocument());
            resetTouchedOnNotNull();
        }
    }
}
