/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq;


import com.yupay.amasua.fv3800.model.jooq.tables.CodeList;
import com.yupay.amasua.fv3800.model.jooq.tables.FilingHistory;
import com.yupay.amasua.fv3800.model.jooq.tables.HeaderInfo;
import com.yupay.amasua.fv3800.model.jooq.tables.Involvement;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna;
import com.yupay.amasua.fv3800.model.jooq.tables.SpouseParty;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>code_list</code>.
     */
    public final CodeList CODE_LIST = CodeList.CODE_LIST;

    /**
     * The table <code>filing_history</code>.
     */
    public final FilingHistory FILING_HISTORY = FilingHistory.FILING_HISTORY;

    /**
     * The table <code>header_info</code>.
     */
    public final HeaderInfo HEADER_INFO = HeaderInfo.HEADER_INFO;

    /**
     * The table <code>involvement</code>.
     */
    public final Involvement INVOLVEMENT = Involvement.INVOLVEMENT;

    /**
     * The table <code>paykuna</code>.
     */
    public final Paykuna PAYKUNA = Paykuna.PAYKUNA;

    /**
     * The table <code>spouse_party</code>.
     */
    public final SpouseParty SPOUSE_PARTY = SpouseParty.SPOUSE_PARTY;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super(DSL.name(""), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CodeList.CODE_LIST,
            FilingHistory.FILING_HISTORY,
            HeaderInfo.HEADER_INFO,
            Involvement.INVOLVEMENT,
            Paykuna.PAYKUNA,
            SpouseParty.SPOUSE_PARTY
        );
    }
}
