/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq;


import com.yupay.amasua.fv3800.model.jooq.tables.CodeList;
import com.yupay.amasua.fv3800.model.jooq.tables.FilingHistory;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UX_CODE_LIST = Internal.createIndex(DSL.name("ux_code_list"), CodeList.CODE_LIST, new OrderField[] { CodeList.CODE_LIST.LIST_ID, CodeList.CODE_LIST.CODE }, true);
    public static final Index UX_FILING_HISTORY_ORDER = Internal.createIndex(DSL.name("ux_filing_history_order"), FilingHistory.FILING_HISTORY, new OrderField[] { FilingHistory.FILING_HISTORY.ORDER_NUMBER }, true);
    public static final Index UX_PAYKUNA_DOI = Internal.createIndex(DSL.name("ux_paykuna_doi"), Paykuna.PAYKUNA, new OrderField[] { Paykuna.PAYKUNA.DOI_TYPE, Paykuna.PAYKUNA.DOI_NUMBER }, true);
}
