/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq;


import com.yupay.amasua.fv3800.model.jooq.tables.CodeList;
import com.yupay.amasua.fv3800.model.jooq.tables.FilingHistory;
import com.yupay.amasua.fv3800.model.jooq.tables.HeaderInfo;
import com.yupay.amasua.fv3800.model.jooq.tables.Involvement;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna;
import com.yupay.amasua.fv3800.model.jooq.tables.SpouseParty;
import com.yupay.amasua.fv3800.model.jooq.tables.records.CodeListRecord;
import com.yupay.amasua.fv3800.model.jooq.tables.records.FilingHistoryRecord;
import com.yupay.amasua.fv3800.model.jooq.tables.records.HeaderInfoRecord;
import com.yupay.amasua.fv3800.model.jooq.tables.records.InvolvementRecord;
import com.yupay.amasua.fv3800.model.jooq.tables.records.PaykunaRecord;
import com.yupay.amasua.fv3800.model.jooq.tables.records.SpousePartyRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CodeListRecord> CODE_LIST__PK_CODE_LIST = Internal.createUniqueKey(CodeList.CODE_LIST, DSL.name("pk_code_list"), new TableField[] { CodeList.CODE_LIST.ID }, true);
    public static final UniqueKey<FilingHistoryRecord> FILING_HISTORY__PK_FILING_HISTORY = Internal.createUniqueKey(FilingHistory.FILING_HISTORY, DSL.name("pk_filing_history"), new TableField[] { FilingHistory.FILING_HISTORY.ID }, true);
    public static final UniqueKey<HeaderInfoRecord> HEADER_INFO__PK_HEADER_INFO = Internal.createUniqueKey(HeaderInfo.HEADER_INFO, DSL.name("pk_header_info"), new TableField[] { HeaderInfo.HEADER_INFO.ID }, true);
    public static final UniqueKey<InvolvementRecord> INVOLVEMENT__PK_INVOLVEMENT = Internal.createUniqueKey(Involvement.INVOLVEMENT, DSL.name("pk_involvement"), new TableField[] { Involvement.INVOLVEMENT.ID }, true);
    public static final UniqueKey<PaykunaRecord> PAYKUNA__PK_PAYKUNA = Internal.createUniqueKey(Paykuna.PAYKUNA, DSL.name("pk_paykuna"), new TableField[] { Paykuna.PAYKUNA.ID }, true);
    public static final UniqueKey<SpousePartyRecord> SPOUSE_PARTY__PK_SPOUSE_PARTY = Internal.createUniqueKey(SpouseParty.SPOUSE_PARTY, DSL.name("pk_spouse_party"), new TableField[] { SpouseParty.SPOUSE_PARTY.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<HeaderInfoRecord, CodeListRecord> HEADER_INFO__FK_HEADER_INFO_PK_CODE_LIST = Internal.createForeignKey(HeaderInfo.HEADER_INFO, DSL.name("fk_header_info_pk_code_list"), new TableField[] { HeaderInfo.HEADER_INFO.COUNTRY }, Keys.CODE_LIST__PK_CODE_LIST, new TableField[] { CodeList.CODE_LIST.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<InvolvementRecord, CodeListRecord> INVOLVEMENT__FK_INVOLVEMENT_PK_CODE_LIST = Internal.createForeignKey(Involvement.INVOLVEMENT, DSL.name("fk_involvement_pk_code_list"), new TableField[] { Involvement.INVOLVEMENT.DEPOSIT_COUNTRY, Involvement.INVOLVEMENT.VALUE_TYPE, Involvement.INVOLVEMENT.INDIRECT_RELATIONSHIP }, Keys.CODE_LIST__PK_CODE_LIST, new TableField[] { CodeList.CODE_LIST.ID, CodeList.CODE_LIST.ID, CodeList.CODE_LIST.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<InvolvementRecord, PaykunaRecord> INVOLVEMENT__FK_INVOLVEMENT_PK_PAYKUNA = Internal.createForeignKey(Involvement.INVOLVEMENT, DSL.name("fk_involvement_pk_paykuna"), new TableField[] { Involvement.INVOLVEMENT.ID }, Keys.PAYKUNA__PK_PAYKUNA, new TableField[] { Paykuna.PAYKUNA.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<PaykunaRecord, CodeListRecord> PAYKUNA__FK_PAYKUNA_PK_CODE_LIST = Internal.createForeignKey(Paykuna.PAYKUNA, DSL.name("fk_paykuna_pk_code_list"), new TableField[] { Paykuna.PAYKUNA.CORPORATE_ROLE, Paykuna.PAYKUNA.COUNTRY_NATIONALITY, Paykuna.PAYKUNA.COUNTRY_RESIDENCE }, Keys.CODE_LIST__PK_CODE_LIST, new TableField[] { CodeList.CODE_LIST.ID, CodeList.CODE_LIST.ID, CodeList.CODE_LIST.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<PaykunaRecord, SpousePartyRecord> PAYKUNA__FK_PAYKUNA_PK_SPOUSE_PARTY = Internal.createForeignKey(Paykuna.PAYKUNA, DSL.name("fk_paykuna_pk_spouse_party"), new TableField[] { Paykuna.PAYKUNA.SPOUSE }, Keys.SPOUSE_PARTY__PK_SPOUSE_PARTY, new TableField[] { SpouseParty.SPOUSE_PARTY.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
