/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq;


import com.yupay.amasua.fv3800.model.jooq.tables.CodeList;
import com.yupay.amasua.fv3800.model.jooq.tables.FilingHistory;
import com.yupay.amasua.fv3800.model.jooq.tables.HeaderInfo;
import com.yupay.amasua.fv3800.model.jooq.tables.Involvement;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna;
import com.yupay.amasua.fv3800.model.jooq.tables.SpouseParty;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>code_list</code>.
     */
    public static final CodeList CODE_LIST = CodeList.CODE_LIST;

    /**
     * The table <code>filing_history</code>.
     */
    public static final FilingHistory FILING_HISTORY = FilingHistory.FILING_HISTORY;

    /**
     * The table <code>header_info</code>.
     */
    public static final HeaderInfo HEADER_INFO = HeaderInfo.HEADER_INFO;

    /**
     * The table <code>involvement</code>.
     */
    public static final Involvement INVOLVEMENT = Involvement.INVOLVEMENT;

    /**
     * The table <code>paykuna</code>.
     */
    public static final Paykuna PAYKUNA = Paykuna.PAYKUNA;

    /**
     * The table <code>spouse_party</code>.
     */
    public static final SpouseParty SPOUSE_PARTY = SpouseParty.SPOUSE_PARTY;
}
