/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.pojos;


import com.yupay.amasua.fv3800.model.enums.ListIds;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeList implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private ListIds listId;
    private String code;
    private String description;
    private Integer sortOrder;
    private String taxAlternateCode;
    private Boolean active;

    public CodeList() {}

    public CodeList(CodeList value) {
        this.id = value.id;
        this.listId = value.listId;
        this.code = value.code;
        this.description = value.description;
        this.sortOrder = value.sortOrder;
        this.taxAlternateCode = value.taxAlternateCode;
        this.active = value.active;
    }

    public CodeList(
        Integer id,
        ListIds listId,
        String code,
        String description,
        Integer sortOrder,
        String taxAlternateCode,
        Boolean active
    ) {
        this.id = id;
        this.listId = listId;
        this.code = code;
        this.description = description;
        this.sortOrder = sortOrder;
        this.taxAlternateCode = taxAlternateCode;
        this.active = active;
    }

    /**
     * Getter for <code>code_list.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>code_list.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>code_list.list_id</code>.
     */
    public ListIds getListId() {
        return this.listId;
    }

    /**
     * Setter for <code>code_list.list_id</code>.
     */
    public void setListId(ListIds listId) {
        this.listId = listId;
    }

    /**
     * Getter for <code>code_list.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>code_list.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>code_list.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>code_list.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>code_list.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Setter for <code>code_list.sort_order</code>.
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * Getter for <code>code_list.tax_alternate_code</code>.
     */
    public String getTaxAlternateCode() {
        return this.taxAlternateCode;
    }

    /**
     * Setter for <code>code_list.tax_alternate_code</code>.
     */
    public void setTaxAlternateCode(String taxAlternateCode) {
        this.taxAlternateCode = taxAlternateCode;
    }

    /**
     * Getter for <code>code_list.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>code_list.active</code>.
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CodeList other = (CodeList) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.listId == null) {
            if (other.listId != null)
                return false;
        }
        else if (!this.listId.equals(other.listId))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!this.sortOrder.equals(other.sortOrder))
            return false;
        if (this.taxAlternateCode == null) {
            if (other.taxAlternateCode != null)
                return false;
        }
        else if (!this.taxAlternateCode.equals(other.taxAlternateCode))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.listId == null) ? 0 : this.listId.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        result = prime * result + ((this.taxAlternateCode == null) ? 0 : this.taxAlternateCode.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CodeList (");

        sb.append(id);
        sb.append(", ").append(listId);
        sb.append(", ").append(code);
        sb.append(", ").append(description);
        sb.append(", ").append(sortOrder);
        sb.append(", ").append(taxAlternateCode);
        sb.append(", ").append(active);

        sb.append(")");
        return sb.toString();
    }
}
