/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilingHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String orderNumber;
    private LocalDate filedAt;
    private String period;

    public FilingHistory() {}

    public FilingHistory(FilingHistory value) {
        this.id = value.id;
        this.orderNumber = value.orderNumber;
        this.filedAt = value.filedAt;
        this.period = value.period;
    }

    public FilingHistory(
        Integer id,
        String orderNumber,
        LocalDate filedAt,
        String period
    ) {
        this.id = id;
        this.orderNumber = orderNumber;
        this.filedAt = filedAt;
        this.period = period;
    }

    /**
     * Getter for <code>filing_history.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>filing_history.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>filing_history.order_number</code>.
     */
    public String getOrderNumber() {
        return this.orderNumber;
    }

    /**
     * Setter for <code>filing_history.order_number</code>.
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * Getter for <code>filing_history.filed_at</code>.
     */
    public LocalDate getFiledAt() {
        return this.filedAt;
    }

    /**
     * Setter for <code>filing_history.filed_at</code>.
     */
    public void setFiledAt(LocalDate filedAt) {
        this.filedAt = filedAt;
    }

    /**
     * Getter for <code>filing_history.period</code>.
     */
    public String getPeriod() {
        return this.period;
    }

    /**
     * Setter for <code>filing_history.period</code>.
     */
    public void setPeriod(String period) {
        this.period = period;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FilingHistory other = (FilingHistory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.orderNumber == null) {
            if (other.orderNumber != null)
                return false;
        }
        else if (!this.orderNumber.equals(other.orderNumber))
            return false;
        if (this.filedAt == null) {
            if (other.filedAt != null)
                return false;
        }
        else if (!this.filedAt.equals(other.filedAt))
            return false;
        if (this.period == null) {
            if (other.period != null)
                return false;
        }
        else if (!this.period.equals(other.period))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.orderNumber == null) ? 0 : this.orderNumber.hashCode());
        result = prime * result + ((this.filedAt == null) ? 0 : this.filedAt.hashCode());
        result = prime * result + ((this.period == null) ? 0 : this.period.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilingHistory (");

        sb.append(id);
        sb.append(", ").append(orderNumber);
        sb.append(", ").append(filedAt);
        sb.append(", ").append(period);

        sb.append(")");
        return sb.toString();
    }
}
