/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.pojos;


import com.yupay.amasua.fv3800.model.enums.EntitySubtype;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HeaderInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String ruc;
    private String periodo;
    private Boolean isIncorporated;
    private EntitySubtype entitySubtype;
    private String entitySubtypeName;
    private String tin;
    private String legalName;
    private Integer country;
    private String mobile;
    private String mail;

    public HeaderInfo() {}

    public HeaderInfo(HeaderInfo value) {
        this.id = value.id;
        this.ruc = value.ruc;
        this.periodo = value.periodo;
        this.isIncorporated = value.isIncorporated;
        this.entitySubtype = value.entitySubtype;
        this.entitySubtypeName = value.entitySubtypeName;
        this.tin = value.tin;
        this.legalName = value.legalName;
        this.country = value.country;
        this.mobile = value.mobile;
        this.mail = value.mail;
    }

    public HeaderInfo(
        Integer id,
        String ruc,
        String periodo,
        Boolean isIncorporated,
        EntitySubtype entitySubtype,
        String entitySubtypeName,
        String tin,
        String legalName,
        Integer country,
        String mobile,
        String mail
    ) {
        this.id = id;
        this.ruc = ruc;
        this.periodo = periodo;
        this.isIncorporated = isIncorporated;
        this.entitySubtype = entitySubtype;
        this.entitySubtypeName = entitySubtypeName;
        this.tin = tin;
        this.legalName = legalName;
        this.country = country;
        this.mobile = mobile;
        this.mail = mail;
    }

    /**
     * Getter for <code>header_info.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>header_info.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>header_info.ruc</code>.
     */
    public String getRuc() {
        return this.ruc;
    }

    /**
     * Setter for <code>header_info.ruc</code>.
     */
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    /**
     * Getter for <code>header_info.periodo</code>.
     */
    public String getPeriodo() {
        return this.periodo;
    }

    /**
     * Setter for <code>header_info.periodo</code>.
     */
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    /**
     * Getter for <code>header_info.is_incorporated</code>.
     */
    public Boolean getIsIncorporated() {
        return this.isIncorporated;
    }

    /**
     * Setter for <code>header_info.is_incorporated</code>.
     */
    public void setIsIncorporated(Boolean isIncorporated) {
        this.isIncorporated = isIncorporated;
    }

    /**
     * Getter for <code>header_info.entity_subtype</code>.
     */
    public EntitySubtype getEntitySubtype() {
        return this.entitySubtype;
    }

    /**
     * Setter for <code>header_info.entity_subtype</code>.
     */
    public void setEntitySubtype(EntitySubtype entitySubtype) {
        this.entitySubtype = entitySubtype;
    }

    /**
     * Getter for <code>header_info.entity_subtype_name</code>.
     */
    public String getEntitySubtypeName() {
        return this.entitySubtypeName;
    }

    /**
     * Setter for <code>header_info.entity_subtype_name</code>.
     */
    public void setEntitySubtypeName(String entitySubtypeName) {
        this.entitySubtypeName = entitySubtypeName;
    }

    /**
     * Getter for <code>header_info.tin</code>.
     */
    public String getTin() {
        return this.tin;
    }

    /**
     * Setter for <code>header_info.tin</code>.
     */
    public void setTin(String tin) {
        this.tin = tin;
    }

    /**
     * Getter for <code>header_info.legal_name</code>.
     */
    public String getLegalName() {
        return this.legalName;
    }

    /**
     * Setter for <code>header_info.legal_name</code>.
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }

    /**
     * Getter for <code>header_info.country</code>.
     */
    public Integer getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>header_info.country</code>.
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * Getter for <code>header_info.mobile</code>.
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     * Setter for <code>header_info.mobile</code>.
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * Getter for <code>header_info.mail</code>.
     */
    public String getMail() {
        return this.mail;
    }

    /**
     * Setter for <code>header_info.mail</code>.
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final HeaderInfo other = (HeaderInfo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ruc == null) {
            if (other.ruc != null)
                return false;
        }
        else if (!this.ruc.equals(other.ruc))
            return false;
        if (this.periodo == null) {
            if (other.periodo != null)
                return false;
        }
        else if (!this.periodo.equals(other.periodo))
            return false;
        if (this.isIncorporated == null) {
            if (other.isIncorporated != null)
                return false;
        }
        else if (!this.isIncorporated.equals(other.isIncorporated))
            return false;
        if (this.entitySubtype == null) {
            if (other.entitySubtype != null)
                return false;
        }
        else if (!this.entitySubtype.equals(other.entitySubtype))
            return false;
        if (this.entitySubtypeName == null) {
            if (other.entitySubtypeName != null)
                return false;
        }
        else if (!this.entitySubtypeName.equals(other.entitySubtypeName))
            return false;
        if (this.tin == null) {
            if (other.tin != null)
                return false;
        }
        else if (!this.tin.equals(other.tin))
            return false;
        if (this.legalName == null) {
            if (other.legalName != null)
                return false;
        }
        else if (!this.legalName.equals(other.legalName))
            return false;
        if (this.country == null) {
            if (other.country != null)
                return false;
        }
        else if (!this.country.equals(other.country))
            return false;
        if (this.mobile == null) {
            if (other.mobile != null)
                return false;
        }
        else if (!this.mobile.equals(other.mobile))
            return false;
        if (this.mail == null) {
            if (other.mail != null)
                return false;
        }
        else if (!this.mail.equals(other.mail))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ruc == null) ? 0 : this.ruc.hashCode());
        result = prime * result + ((this.periodo == null) ? 0 : this.periodo.hashCode());
        result = prime * result + ((this.isIncorporated == null) ? 0 : this.isIncorporated.hashCode());
        result = prime * result + ((this.entitySubtype == null) ? 0 : this.entitySubtype.hashCode());
        result = prime * result + ((this.entitySubtypeName == null) ? 0 : this.entitySubtypeName.hashCode());
        result = prime * result + ((this.tin == null) ? 0 : this.tin.hashCode());
        result = prime * result + ((this.legalName == null) ? 0 : this.legalName.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.mobile == null) ? 0 : this.mobile.hashCode());
        result = prime * result + ((this.mail == null) ? 0 : this.mail.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HeaderInfo (");

        sb.append(id);
        sb.append(", ").append(ruc);
        sb.append(", ").append(periodo);
        sb.append(", ").append(isIncorporated);
        sb.append(", ").append(entitySubtype);
        sb.append(", ").append(entitySubtypeName);
        sb.append(", ").append(tin);
        sb.append(", ").append(legalName);
        sb.append(", ").append(country);
        sb.append(", ").append(mobile);
        sb.append(", ").append(mail);

        sb.append(")");
        return sb.toString();
    }
}
