/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.pojos;


import com.yupay.amasua.fv3800.model.enums.DoiType;
import com.yupay.amasua.fv3800.model.enums.IndirectType;

import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Involvement implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Boolean hasOwnership;
    private Boolean hasControl;
    private Boolean hasSeniorMgmt;
    private Boolean isDirect;
    private IndirectType indirectType;
    private Integer indirectRelationship;
    private DoiType titularDoiType;
    private String titularDoiNumber;
    private Integer valueType;
    private BigDecimal valueCount;
    private BigDecimal valueNominal;
    private BigDecimal participationPercentage;
    private Boolean hasVotingRights;
    private Integer depositCountry;
    private String controlDescription;

    public Involvement() {}

    public Involvement(Involvement value) {
        this.id = value.id;
        this.hasOwnership = value.hasOwnership;
        this.hasControl = value.hasControl;
        this.hasSeniorMgmt = value.hasSeniorMgmt;
        this.isDirect = value.isDirect;
        this.indirectType = value.indirectType;
        this.indirectRelationship = value.indirectRelationship;
        this.titularDoiType = value.titularDoiType;
        this.titularDoiNumber = value.titularDoiNumber;
        this.valueType = value.valueType;
        this.valueCount = value.valueCount;
        this.valueNominal = value.valueNominal;
        this.participationPercentage = value.participationPercentage;
        this.hasVotingRights = value.hasVotingRights;
        this.depositCountry = value.depositCountry;
        this.controlDescription = value.controlDescription;
    }

    public Involvement(
        Integer id,
        Boolean hasOwnership,
        Boolean hasControl,
        Boolean hasSeniorMgmt,
        Boolean isDirect,
        IndirectType indirectType,
        Integer indirectRelationship,
        DoiType titularDoiType,
        String titularDoiNumber,
        Integer valueType,
        BigDecimal valueCount,
        BigDecimal valueNominal,
        BigDecimal participationPercentage,
        Boolean hasVotingRights,
        Integer depositCountry,
        String controlDescription
    ) {
        this.id = id;
        this.hasOwnership = hasOwnership;
        this.hasControl = hasControl;
        this.hasSeniorMgmt = hasSeniorMgmt;
        this.isDirect = isDirect;
        this.indirectType = indirectType;
        this.indirectRelationship = indirectRelationship;
        this.titularDoiType = titularDoiType;
        this.titularDoiNumber = titularDoiNumber;
        this.valueType = valueType;
        this.valueCount = valueCount;
        this.valueNominal = valueNominal;
        this.participationPercentage = participationPercentage;
        this.hasVotingRights = hasVotingRights;
        this.depositCountry = depositCountry;
        this.controlDescription = controlDescription;
    }

    /**
     * Getter for <code>involvement.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>involvement.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>involvement.has_ownership</code>.
     */
    public Boolean getHasOwnership() {
        return this.hasOwnership;
    }

    /**
     * Setter for <code>involvement.has_ownership</code>.
     */
    public void setHasOwnership(Boolean hasOwnership) {
        this.hasOwnership = hasOwnership;
    }

    /**
     * Getter for <code>involvement.has_control</code>.
     */
    public Boolean getHasControl() {
        return this.hasControl;
    }

    /**
     * Setter for <code>involvement.has_control</code>.
     */
    public void setHasControl(Boolean hasControl) {
        this.hasControl = hasControl;
    }

    /**
     * Getter for <code>involvement.has_senior_mgmt</code>.
     */
    public Boolean getHasSeniorMgmt() {
        return this.hasSeniorMgmt;
    }

    /**
     * Setter for <code>involvement.has_senior_mgmt</code>.
     */
    public void setHasSeniorMgmt(Boolean hasSeniorMgmt) {
        this.hasSeniorMgmt = hasSeniorMgmt;
    }

    /**
     * Getter for <code>involvement.is_direct</code>.
     */
    public Boolean getIsDirect() {
        return this.isDirect;
    }

    /**
     * Setter for <code>involvement.is_direct</code>.
     */
    public void setIsDirect(Boolean isDirect) {
        this.isDirect = isDirect;
    }

    /**
     * Getter for <code>involvement.indirect_type</code>.
     */
    public IndirectType getIndirectType() {
        return this.indirectType;
    }

    /**
     * Setter for <code>involvement.indirect_type</code>.
     */
    public void setIndirectType(IndirectType indirectType) {
        this.indirectType = indirectType;
    }

    /**
     * Getter for <code>involvement.indirect_relationship</code>.
     */
    public Integer getIndirectRelationship() {
        return this.indirectRelationship;
    }

    /**
     * Setter for <code>involvement.indirect_relationship</code>.
     */
    public void setIndirectRelationship(Integer indirectRelationship) {
        this.indirectRelationship = indirectRelationship;
    }

    /**
     * Getter for <code>involvement.titular_doi_type</code>.
     */
    public DoiType getTitularDoiType() {
        return this.titularDoiType;
    }

    /**
     * Setter for <code>involvement.titular_doi_type</code>.
     */
    public void setTitularDoiType(DoiType titularDoiType) {
        this.titularDoiType = titularDoiType;
    }

    /**
     * Getter for <code>involvement.titular_doi_number</code>.
     */
    public String getTitularDoiNumber() {
        return this.titularDoiNumber;
    }

    /**
     * Setter for <code>involvement.titular_doi_number</code>.
     */
    public void setTitularDoiNumber(String titularDoiNumber) {
        this.titularDoiNumber = titularDoiNumber;
    }

    /**
     * Getter for <code>involvement.value_type</code>.
     */
    public Integer getValueType() {
        return this.valueType;
    }

    /**
     * Setter for <code>involvement.value_type</code>.
     */
    public void setValueType(Integer valueType) {
        this.valueType = valueType;
    }

    /**
     * Getter for <code>involvement.value_count</code>.
     */
    public BigDecimal getValueCount() {
        return this.valueCount;
    }

    /**
     * Setter for <code>involvement.value_count</code>.
     */
    public void setValueCount(BigDecimal valueCount) {
        this.valueCount = valueCount;
    }

    /**
     * Getter for <code>involvement.value_nominal</code>.
     */
    public BigDecimal getValueNominal() {
        return this.valueNominal;
    }

    /**
     * Setter for <code>involvement.value_nominal</code>.
     */
    public void setValueNominal(BigDecimal valueNominal) {
        this.valueNominal = valueNominal;
    }

    /**
     * Getter for <code>involvement.participation_percentage</code>.
     */
    public BigDecimal getParticipationPercentage() {
        return this.participationPercentage;
    }

    /**
     * Setter for <code>involvement.participation_percentage</code>.
     */
    public void setParticipationPercentage(BigDecimal participationPercentage) {
        this.participationPercentage = participationPercentage;
    }

    /**
     * Getter for <code>involvement.has_voting_rights</code>.
     */
    public Boolean getHasVotingRights() {
        return this.hasVotingRights;
    }

    /**
     * Setter for <code>involvement.has_voting_rights</code>.
     */
    public void setHasVotingRights(Boolean hasVotingRights) {
        this.hasVotingRights = hasVotingRights;
    }

    /**
     * Getter for <code>involvement.deposit_country</code>.
     */
    public Integer getDepositCountry() {
        return this.depositCountry;
    }

    /**
     * Setter for <code>involvement.deposit_country</code>.
     */
    public void setDepositCountry(Integer depositCountry) {
        this.depositCountry = depositCountry;
    }

    /**
     * Getter for <code>involvement.control_description</code>.
     */
    public String getControlDescription() {
        return this.controlDescription;
    }

    /**
     * Setter for <code>involvement.control_description</code>.
     */
    public void setControlDescription(String controlDescription) {
        this.controlDescription = controlDescription;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Involvement other = (Involvement) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.hasOwnership == null) {
            if (other.hasOwnership != null)
                return false;
        }
        else if (!this.hasOwnership.equals(other.hasOwnership))
            return false;
        if (this.hasControl == null) {
            if (other.hasControl != null)
                return false;
        }
        else if (!this.hasControl.equals(other.hasControl))
            return false;
        if (this.hasSeniorMgmt == null) {
            if (other.hasSeniorMgmt != null)
                return false;
        }
        else if (!this.hasSeniorMgmt.equals(other.hasSeniorMgmt))
            return false;
        if (this.isDirect == null) {
            if (other.isDirect != null)
                return false;
        }
        else if (!this.isDirect.equals(other.isDirect))
            return false;
        if (this.indirectType == null) {
            if (other.indirectType != null)
                return false;
        }
        else if (!this.indirectType.equals(other.indirectType))
            return false;
        if (this.indirectRelationship == null) {
            if (other.indirectRelationship != null)
                return false;
        }
        else if (!this.indirectRelationship.equals(other.indirectRelationship))
            return false;
        if (this.titularDoiType == null) {
            if (other.titularDoiType != null)
                return false;
        }
        else if (!this.titularDoiType.equals(other.titularDoiType))
            return false;
        if (this.titularDoiNumber == null) {
            if (other.titularDoiNumber != null)
                return false;
        }
        else if (!this.titularDoiNumber.equals(other.titularDoiNumber))
            return false;
        if (this.valueType == null) {
            if (other.valueType != null)
                return false;
        }
        else if (!this.valueType.equals(other.valueType))
            return false;
        if (this.valueCount == null) {
            if (other.valueCount != null)
                return false;
        }
        else if (!this.valueCount.equals(other.valueCount))
            return false;
        if (this.valueNominal == null) {
            if (other.valueNominal != null)
                return false;
        }
        else if (!this.valueNominal.equals(other.valueNominal))
            return false;
        if (this.participationPercentage == null) {
            if (other.participationPercentage != null)
                return false;
        }
        else if (!this.participationPercentage.equals(other.participationPercentage))
            return false;
        if (this.hasVotingRights == null) {
            if (other.hasVotingRights != null)
                return false;
        }
        else if (!this.hasVotingRights.equals(other.hasVotingRights))
            return false;
        if (this.depositCountry == null) {
            if (other.depositCountry != null)
                return false;
        }
        else if (!this.depositCountry.equals(other.depositCountry))
            return false;
        if (this.controlDescription == null) {
            if (other.controlDescription != null)
                return false;
        }
        else if (!this.controlDescription.equals(other.controlDescription))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.hasOwnership == null) ? 0 : this.hasOwnership.hashCode());
        result = prime * result + ((this.hasControl == null) ? 0 : this.hasControl.hashCode());
        result = prime * result + ((this.hasSeniorMgmt == null) ? 0 : this.hasSeniorMgmt.hashCode());
        result = prime * result + ((this.isDirect == null) ? 0 : this.isDirect.hashCode());
        result = prime * result + ((this.indirectType == null) ? 0 : this.indirectType.hashCode());
        result = prime * result + ((this.indirectRelationship == null) ? 0 : this.indirectRelationship.hashCode());
        result = prime * result + ((this.titularDoiType == null) ? 0 : this.titularDoiType.hashCode());
        result = prime * result + ((this.titularDoiNumber == null) ? 0 : this.titularDoiNumber.hashCode());
        result = prime * result + ((this.valueType == null) ? 0 : this.valueType.hashCode());
        result = prime * result + ((this.valueCount == null) ? 0 : this.valueCount.hashCode());
        result = prime * result + ((this.valueNominal == null) ? 0 : this.valueNominal.hashCode());
        result = prime * result + ((this.participationPercentage == null) ? 0 : this.participationPercentage.hashCode());
        result = prime * result + ((this.hasVotingRights == null) ? 0 : this.hasVotingRights.hashCode());
        result = prime * result + ((this.depositCountry == null) ? 0 : this.depositCountry.hashCode());
        result = prime * result + ((this.controlDescription == null) ? 0 : this.controlDescription.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Involvement (");

        sb.append(id);
        sb.append(", ").append(hasOwnership);
        sb.append(", ").append(hasControl);
        sb.append(", ").append(hasSeniorMgmt);
        sb.append(", ").append(isDirect);
        sb.append(", ").append(indirectType);
        sb.append(", ").append(indirectRelationship);
        sb.append(", ").append(titularDoiType);
        sb.append(", ").append(titularDoiNumber);
        sb.append(", ").append(valueType);
        sb.append(", ").append(valueCount);
        sb.append(", ").append(valueNominal);
        sb.append(", ").append(participationPercentage);
        sb.append(", ").append(hasVotingRights);
        sb.append(", ").append(depositCountry);
        sb.append(", ").append(controlDescription);

        sb.append(")");
        return sb.toString();
    }
}
