/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.pojos;


import com.yupay.amasua.fv3800.model.enums.DoiType;
import com.yupay.amasua.fv3800.model.enums.MaritalStatus;

import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Paykuna implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Boolean resident;
    private DoiType doiType;
    private String doiNumber;
    private String name;
    private Integer countryResidence;
    private LocalDate birthday;
    private Integer countryNationality;
    private String address;
    private Integer corporateRole;
    private String phone;
    private MaritalStatus maritalStatus;
    private LocalDate noticeDate;
    private Integer spouse;
    private Boolean isLegalRepresentative;

    public Paykuna() {}

    public Paykuna(Paykuna value) {
        this.id = value.id;
        this.resident = value.resident;
        this.doiType = value.doiType;
        this.doiNumber = value.doiNumber;
        this.name = value.name;
        this.countryResidence = value.countryResidence;
        this.birthday = value.birthday;
        this.countryNationality = value.countryNationality;
        this.address = value.address;
        this.corporateRole = value.corporateRole;
        this.phone = value.phone;
        this.maritalStatus = value.maritalStatus;
        this.noticeDate = value.noticeDate;
        this.spouse = value.spouse;
        this.isLegalRepresentative = value.isLegalRepresentative;
    }

    public Paykuna(
        Integer id,
        Boolean resident,
        DoiType doiType,
        String doiNumber,
        String name,
        Integer countryResidence,
        LocalDate birthday,
        Integer countryNationality,
        String address,
        Integer corporateRole,
        String phone,
        MaritalStatus maritalStatus,
        LocalDate noticeDate,
        Integer spouse,
        Boolean isLegalRepresentative
    ) {
        this.id = id;
        this.resident = resident;
        this.doiType = doiType;
        this.doiNumber = doiNumber;
        this.name = name;
        this.countryResidence = countryResidence;
        this.birthday = birthday;
        this.countryNationality = countryNationality;
        this.address = address;
        this.corporateRole = corporateRole;
        this.phone = phone;
        this.maritalStatus = maritalStatus;
        this.noticeDate = noticeDate;
        this.spouse = spouse;
        this.isLegalRepresentative = isLegalRepresentative;
    }

    /**
     * Getter for <code>paykuna.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>paykuna.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>paykuna.resident</code>.
     */
    public Boolean getResident() {
        return this.resident;
    }

    /**
     * Setter for <code>paykuna.resident</code>.
     */
    public void setResident(Boolean resident) {
        this.resident = resident;
    }

    /**
     * Getter for <code>paykuna.doi_type</code>.
     */
    public DoiType getDoiType() {
        return this.doiType;
    }

    /**
     * Setter for <code>paykuna.doi_type</code>.
     */
    public void setDoiType(DoiType doiType) {
        this.doiType = doiType;
    }

    /**
     * Getter for <code>paykuna.doi_number</code>.
     */
    public String getDoiNumber() {
        return this.doiNumber;
    }

    /**
     * Setter for <code>paykuna.doi_number</code>.
     */
    public void setDoiNumber(String doiNumber) {
        this.doiNumber = doiNumber;
    }

    /**
     * Getter for <code>paykuna.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>paykuna.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>paykuna.country_residence</code>.
     */
    public Integer getCountryResidence() {
        return this.countryResidence;
    }

    /**
     * Setter for <code>paykuna.country_residence</code>.
     */
    public void setCountryResidence(Integer countryResidence) {
        this.countryResidence = countryResidence;
    }

    /**
     * Getter for <code>paykuna.birthday</code>.
     */
    public LocalDate getBirthday() {
        return this.birthday;
    }

    /**
     * Setter for <code>paykuna.birthday</code>.
     */
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    /**
     * Getter for <code>paykuna.country_nationality</code>.
     */
    public Integer getCountryNationality() {
        return this.countryNationality;
    }

    /**
     * Setter for <code>paykuna.country_nationality</code>.
     */
    public void setCountryNationality(Integer countryNationality) {
        this.countryNationality = countryNationality;
    }

    /**
     * Getter for <code>paykuna.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>paykuna.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>paykuna.corporate_role</code>.
     */
    public Integer getCorporateRole() {
        return this.corporateRole;
    }

    /**
     * Setter for <code>paykuna.corporate_role</code>.
     */
    public void setCorporateRole(Integer corporateRole) {
        this.corporateRole = corporateRole;
    }

    /**
     * Getter for <code>paykuna.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>paykuna.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>paykuna.marital_status</code>.
     */
    public MaritalStatus getMaritalStatus() {
        return this.maritalStatus;
    }

    /**
     * Setter for <code>paykuna.marital_status</code>.
     */
    public void setMaritalStatus(MaritalStatus maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * Getter for <code>paykuna.notice_date</code>.
     */
    public LocalDate getNoticeDate() {
        return this.noticeDate;
    }

    /**
     * Setter for <code>paykuna.notice_date</code>.
     */
    public void setNoticeDate(LocalDate noticeDate) {
        this.noticeDate = noticeDate;
    }

    /**
     * Getter for <code>paykuna.spouse</code>.
     */
    public Integer getSpouse() {
        return this.spouse;
    }

    /**
     * Setter for <code>paykuna.spouse</code>.
     */
    public void setSpouse(Integer spouse) {
        this.spouse = spouse;
    }

    /**
     * Getter for <code>paykuna.is_legal_representative</code>.
     */
    public Boolean getIsLegalRepresentative() {
        return this.isLegalRepresentative;
    }

    /**
     * Setter for <code>paykuna.is_legal_representative</code>.
     */
    public void setIsLegalRepresentative(Boolean isLegalRepresentative) {
        this.isLegalRepresentative = isLegalRepresentative;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Paykuna other = (Paykuna) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.resident == null) {
            if (other.resident != null)
                return false;
        }
        else if (!this.resident.equals(other.resident))
            return false;
        if (this.doiType == null) {
            if (other.doiType != null)
                return false;
        }
        else if (!this.doiType.equals(other.doiType))
            return false;
        if (this.doiNumber == null) {
            if (other.doiNumber != null)
                return false;
        }
        else if (!this.doiNumber.equals(other.doiNumber))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.countryResidence == null) {
            if (other.countryResidence != null)
                return false;
        }
        else if (!this.countryResidence.equals(other.countryResidence))
            return false;
        if (this.birthday == null) {
            if (other.birthday != null)
                return false;
        }
        else if (!this.birthday.equals(other.birthday))
            return false;
        if (this.countryNationality == null) {
            if (other.countryNationality != null)
                return false;
        }
        else if (!this.countryNationality.equals(other.countryNationality))
            return false;
        if (this.address == null) {
            if (other.address != null)
                return false;
        }
        else if (!this.address.equals(other.address))
            return false;
        if (this.corporateRole == null) {
            if (other.corporateRole != null)
                return false;
        }
        else if (!this.corporateRole.equals(other.corporateRole))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.maritalStatus == null) {
            if (other.maritalStatus != null)
                return false;
        }
        else if (!this.maritalStatus.equals(other.maritalStatus))
            return false;
        if (this.noticeDate == null) {
            if (other.noticeDate != null)
                return false;
        }
        else if (!this.noticeDate.equals(other.noticeDate))
            return false;
        if (this.spouse == null) {
            if (other.spouse != null)
                return false;
        }
        else if (!this.spouse.equals(other.spouse))
            return false;
        if (this.isLegalRepresentative == null) {
            if (other.isLegalRepresentative != null)
                return false;
        }
        else if (!this.isLegalRepresentative.equals(other.isLegalRepresentative))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.resident == null) ? 0 : this.resident.hashCode());
        result = prime * result + ((this.doiType == null) ? 0 : this.doiType.hashCode());
        result = prime * result + ((this.doiNumber == null) ? 0 : this.doiNumber.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.countryResidence == null) ? 0 : this.countryResidence.hashCode());
        result = prime * result + ((this.birthday == null) ? 0 : this.birthday.hashCode());
        result = prime * result + ((this.countryNationality == null) ? 0 : this.countryNationality.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.corporateRole == null) ? 0 : this.corporateRole.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.maritalStatus == null) ? 0 : this.maritalStatus.hashCode());
        result = prime * result + ((this.noticeDate == null) ? 0 : this.noticeDate.hashCode());
        result = prime * result + ((this.spouse == null) ? 0 : this.spouse.hashCode());
        result = prime * result + ((this.isLegalRepresentative == null) ? 0 : this.isLegalRepresentative.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Paykuna (");

        sb.append(id);
        sb.append(", ").append(resident);
        sb.append(", ").append(doiType);
        sb.append(", ").append(doiNumber);
        sb.append(", ").append(name);
        sb.append(", ").append(countryResidence);
        sb.append(", ").append(birthday);
        sb.append(", ").append(countryNationality);
        sb.append(", ").append(address);
        sb.append(", ").append(corporateRole);
        sb.append(", ").append(phone);
        sb.append(", ").append(maritalStatus);
        sb.append(", ").append(noticeDate);
        sb.append(", ").append(spouse);
        sb.append(", ").append(isLegalRepresentative);

        sb.append(")");
        return sb.toString();
    }
}
