/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpouseParty implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String doiNumber;
    private LocalDate certainDate;
    private String certainDocument;

    public SpouseParty() {}

    public SpouseParty(SpouseParty value) {
        this.id = value.id;
        this.name = value.name;
        this.doiNumber = value.doiNumber;
        this.certainDate = value.certainDate;
        this.certainDocument = value.certainDocument;
    }

    public SpouseParty(
        Integer id,
        String name,
        String doiNumber,
        LocalDate certainDate,
        String certainDocument
    ) {
        this.id = id;
        this.name = name;
        this.doiNumber = doiNumber;
        this.certainDate = certainDate;
        this.certainDocument = certainDocument;
    }

    /**
     * Getter for <code>spouse_party.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>spouse_party.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>spouse_party.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>spouse_party.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>spouse_party.doi_number</code>.
     */
    public String getDoiNumber() {
        return this.doiNumber;
    }

    /**
     * Setter for <code>spouse_party.doi_number</code>.
     */
    public void setDoiNumber(String doiNumber) {
        this.doiNumber = doiNumber;
    }

    /**
     * Getter for <code>spouse_party.certain_date</code>.
     */
    public LocalDate getCertainDate() {
        return this.certainDate;
    }

    /**
     * Setter for <code>spouse_party.certain_date</code>.
     */
    public void setCertainDate(LocalDate certainDate) {
        this.certainDate = certainDate;
    }

    /**
     * Getter for <code>spouse_party.certain_document</code>.
     */
    public String getCertainDocument() {
        return this.certainDocument;
    }

    /**
     * Setter for <code>spouse_party.certain_document</code>.
     */
    public void setCertainDocument(String certainDocument) {
        this.certainDocument = certainDocument;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SpouseParty other = (SpouseParty) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.doiNumber == null) {
            if (other.doiNumber != null)
                return false;
        }
        else if (!this.doiNumber.equals(other.doiNumber))
            return false;
        if (this.certainDate == null) {
            if (other.certainDate != null)
                return false;
        }
        else if (!this.certainDate.equals(other.certainDate))
            return false;
        if (this.certainDocument == null) {
            if (other.certainDocument != null)
                return false;
        }
        else if (!this.certainDocument.equals(other.certainDocument))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.doiNumber == null) ? 0 : this.doiNumber.hashCode());
        result = prime * result + ((this.certainDate == null) ? 0 : this.certainDate.hashCode());
        result = prime * result + ((this.certainDocument == null) ? 0 : this.certainDocument.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SpouseParty (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(doiNumber);
        sb.append(", ").append(certainDate);
        sb.append(", ").append(certainDocument);

        sb.append(")");
        return sb.toString();
    }
}
