/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables;


import com.yupay.amasua.fv3800.model.enums.ListIds;
import com.yupay.amasua.fv3800.model.jooq.DefaultSchema;
import com.yupay.amasua.fv3800.model.jooq.Indexes;
import com.yupay.amasua.fv3800.model.jooq.Keys;
import com.yupay.amasua.fv3800.model.jooq.converters.ListIdsConverter;
import com.yupay.amasua.fv3800.model.jooq.tables.HeaderInfo.HeaderInfoPath;
import com.yupay.amasua.fv3800.model.jooq.tables.Involvement.InvolvementPath;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna.PaykunaPath;
import com.yupay.amasua.fv3800.model.jooq.tables.records.CodeListRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeList extends TableImpl<CodeListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>code_list</code>
     */
    public static final CodeList CODE_LIST = new CodeList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeListRecord> getRecordType() {
        return CodeListRecord.class;
    }

    /**
     * The column <code>code_list.id</code>.
     */
    public final TableField<CodeListRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>code_list.list_id</code>.
     */
    public final TableField<CodeListRecord, ListIds> LIST_ID = createField(DSL.name("list_id"), SQLDataType.VARCHAR.nullable(false), this, "", new ListIdsConverter());

    /**
     * The column <code>code_list.code</code>.
     */
    public final TableField<CodeListRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>code_list.description</code>.
     */
    public final TableField<CodeListRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>code_list.sort_order</code>.
     */
    public final TableField<CodeListRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>code_list.tax_alternate_code</code>.
     */
    public final TableField<CodeListRecord, String> TAX_ALTERNATE_CODE = createField(DSL.name("tax_alternate_code"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>code_list.active</code>.
     */
    public final TableField<CodeListRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private CodeList(Name alias, Table<CodeListRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeList(Name alias, Table<CodeListRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>code_list</code> table reference
     */
    public CodeList(String alias) {
        this(DSL.name(alias), CODE_LIST);
    }

    /**
     * Create an aliased <code>code_list</code> table reference
     */
    public CodeList(Name alias) {
        this(alias, CODE_LIST);
    }

    /**
     * Create a <code>code_list</code> table reference
     */
    public CodeList() {
        this(DSL.name("code_list"), null);
    }

    public <O extends Record> CodeList(Table<O> path, ForeignKey<O, CodeListRecord> childPath, InverseForeignKey<O, CodeListRecord> parentPath) {
        super(path, childPath, parentPath, CODE_LIST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeListPath extends CodeList implements Path<CodeListRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeListPath(Table<O> path, ForeignKey<O, CodeListRecord> childPath, InverseForeignKey<O, CodeListRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeListPath(Name alias, Table<CodeListRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeListPath as(String alias) {
            return new CodeListPath(DSL.name(alias), this);
        }

        @Override
        public CodeListPath as(Name alias) {
            return new CodeListPath(alias, this);
        }

        @Override
        public CodeListPath as(Table<?> alias) {
            return new CodeListPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UX_CODE_LIST);
    }

    @Override
    public UniqueKey<CodeListRecord> getPrimaryKey() {
        return Keys.CODE_LIST__PK_CODE_LIST;
    }

    private transient HeaderInfoPath _headerInfo;

    /**
     * Get the implicit to-many join path to the <code>header_info</code> table
     */
    public HeaderInfoPath headerInfo() {
        if (_headerInfo == null)
            _headerInfo = new HeaderInfoPath(this, null, Keys.HEADER_INFO__FK_HEADER_INFO_PK_CODE_LIST.getInverseKey());

        return _headerInfo;
    }

    private transient InvolvementPath _involvement;

    /**
     * Get the implicit to-many join path to the <code>involvement</code> table
     */
    public InvolvementPath involvement() {
        if (_involvement == null)
            _involvement = new InvolvementPath(this, null, Keys.INVOLVEMENT__FK_INVOLVEMENT_PK_CODE_LIST.getInverseKey());

        return _involvement;
    }

    private transient PaykunaPath _paykuna;

    /**
     * Get the implicit to-many join path to the <code>paykuna</code> table
     */
    public PaykunaPath paykuna() {
        if (_paykuna == null)
            _paykuna = new PaykunaPath(this, null, Keys.PAYKUNA__FK_PAYKUNA_PK_CODE_LIST.getInverseKey());

        return _paykuna;
    }

    @Override
    public List<Check<CodeListRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name(""), "`active` in (0, 1)", true)
        );
    }

    @Override
    public CodeList as(String alias) {
        return new CodeList(DSL.name(alias), this);
    }

    @Override
    public CodeList as(Name alias) {
        return new CodeList(alias, this);
    }

    @Override
    public CodeList as(Table<?> alias) {
        return new CodeList(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeList rename(String name) {
        return new CodeList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeList rename(Name name) {
        return new CodeList(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeList rename(Table<?> name) {
        return new CodeList(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeList where(Condition condition) {
        return new CodeList(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeList where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeList where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeList where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeList where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeList where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeList where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeList where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeList whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeList whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
