/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables;


import com.yupay.amasua.fv3800.model.jooq.DefaultSchema;
import com.yupay.amasua.fv3800.model.jooq.Indexes;
import com.yupay.amasua.fv3800.model.jooq.Keys;
import com.yupay.amasua.fv3800.model.jooq.converters.EpochDaysConverter;
import com.yupay.amasua.fv3800.model.jooq.tables.records.FilingHistoryRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilingHistory extends TableImpl<FilingHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>filing_history</code>
     */
    public static final FilingHistory FILING_HISTORY = new FilingHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FilingHistoryRecord> getRecordType() {
        return FilingHistoryRecord.class;
    }

    /**
     * The column <code>filing_history.id</code>.
     */
    public final TableField<FilingHistoryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>filing_history.order_number</code>.
     */
    public final TableField<FilingHistoryRecord, String> ORDER_NUMBER = createField(DSL.name("order_number"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>filing_history.filed_at</code>.
     */
    public final TableField<FilingHistoryRecord, LocalDate> FILED_AT = createField(DSL.name("filed_at"), SQLDataType.BIGINT.nullable(false), this, "", new EpochDaysConverter());

    /**
     * The column <code>filing_history.period</code>.
     */
    public final TableField<FilingHistoryRecord, String> PERIOD = createField(DSL.name("period"), SQLDataType.CLOB.nullable(false), this, "");

    private FilingHistory(Name alias, Table<FilingHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FilingHistory(Name alias, Table<FilingHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>filing_history</code> table reference
     */
    public FilingHistory(String alias) {
        this(DSL.name(alias), FILING_HISTORY);
    }

    /**
     * Create an aliased <code>filing_history</code> table reference
     */
    public FilingHistory(Name alias) {
        this(alias, FILING_HISTORY);
    }

    /**
     * Create a <code>filing_history</code> table reference
     */
    public FilingHistory() {
        this(DSL.name("filing_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UX_FILING_HISTORY_ORDER);
    }

    @Override
    public UniqueKey<FilingHistoryRecord> getPrimaryKey() {
        return Keys.FILING_HISTORY__PK_FILING_HISTORY;
    }

    @Override
    public FilingHistory as(String alias) {
        return new FilingHistory(DSL.name(alias), this);
    }

    @Override
    public FilingHistory as(Name alias) {
        return new FilingHistory(alias, this);
    }

    @Override
    public FilingHistory as(Table<?> alias) {
        return new FilingHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FilingHistory rename(String name) {
        return new FilingHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FilingHistory rename(Name name) {
        return new FilingHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FilingHistory rename(Table<?> name) {
        return new FilingHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilingHistory where(Condition condition) {
        return new FilingHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilingHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilingHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilingHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilingHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilingHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilingHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilingHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilingHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilingHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
