/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables;


import com.yupay.amasua.fv3800.model.enums.EntitySubtype;
import com.yupay.amasua.fv3800.model.jooq.DefaultSchema;
import com.yupay.amasua.fv3800.model.jooq.Keys;
import com.yupay.amasua.fv3800.model.jooq.converters.EntitySubtypeConverter;
import com.yupay.amasua.fv3800.model.jooq.tables.CodeList.CodeListPath;
import com.yupay.amasua.fv3800.model.jooq.tables.records.HeaderInfoRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HeaderInfo extends TableImpl<HeaderInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>header_info</code>
     */
    public static final HeaderInfo HEADER_INFO = new HeaderInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HeaderInfoRecord> getRecordType() {
        return HeaderInfoRecord.class;
    }

    /**
     * The column <code>header_info.id</code>.
     */
    public final TableField<HeaderInfoRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>header_info.ruc</code>.
     */
    public final TableField<HeaderInfoRecord, String> RUC = createField(DSL.name("ruc"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>header_info.periodo</code>.
     */
    public final TableField<HeaderInfoRecord, String> PERIODO = createField(DSL.name("periodo"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>header_info.is_incorporated</code>.
     */
    public final TableField<HeaderInfoRecord, Boolean> IS_INCORPORATED = createField(DSL.name("is_incorporated"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>header_info.entity_subtype</code>.
     */
    public final TableField<HeaderInfoRecord, EntitySubtype> ENTITY_SUBTYPE = createField(DSL.name("entity_subtype"), SQLDataType.VARCHAR, this, "", new EntitySubtypeConverter());

    /**
     * The column <code>header_info.entity_subtype_name</code>.
     */
    public final TableField<HeaderInfoRecord, String> ENTITY_SUBTYPE_NAME = createField(DSL.name("entity_subtype_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>header_info.tin</code>.
     */
    public final TableField<HeaderInfoRecord, String> TIN = createField(DSL.name("tin"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>header_info.legal_name</code>.
     */
    public final TableField<HeaderInfoRecord, String> LEGAL_NAME = createField(DSL.name("legal_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>header_info.country</code>.
     */
    public final TableField<HeaderInfoRecord, Integer> COUNTRY = createField(DSL.name("country"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>header_info.mobile</code>.
     */
    public final TableField<HeaderInfoRecord, String> MOBILE = createField(DSL.name("mobile"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>header_info.mail</code>.
     */
    public final TableField<HeaderInfoRecord, String> MAIL = createField(DSL.name("mail"), SQLDataType.CLOB.nullable(false), this, "");

    private HeaderInfo(Name alias, Table<HeaderInfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HeaderInfo(Name alias, Table<HeaderInfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>header_info</code> table reference
     */
    public HeaderInfo(String alias) {
        this(DSL.name(alias), HEADER_INFO);
    }

    /**
     * Create an aliased <code>header_info</code> table reference
     */
    public HeaderInfo(Name alias) {
        this(alias, HEADER_INFO);
    }

    /**
     * Create a <code>header_info</code> table reference
     */
    public HeaderInfo() {
        this(DSL.name("header_info"), null);
    }

    public <O extends Record> HeaderInfo(Table<O> path, ForeignKey<O, HeaderInfoRecord> childPath, InverseForeignKey<O, HeaderInfoRecord> parentPath) {
        super(path, childPath, parentPath, HEADER_INFO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HeaderInfoPath extends HeaderInfo implements Path<HeaderInfoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HeaderInfoPath(Table<O> path, ForeignKey<O, HeaderInfoRecord> childPath, InverseForeignKey<O, HeaderInfoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HeaderInfoPath(Name alias, Table<HeaderInfoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HeaderInfoPath as(String alias) {
            return new HeaderInfoPath(DSL.name(alias), this);
        }

        @Override
        public HeaderInfoPath as(Name alias) {
            return new HeaderInfoPath(alias, this);
        }

        @Override
        public HeaderInfoPath as(Table<?> alias) {
            return new HeaderInfoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<HeaderInfoRecord> getPrimaryKey() {
        return Keys.HEADER_INFO__PK_HEADER_INFO;
    }

    @Override
    public List<ForeignKey<HeaderInfoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HEADER_INFO__FK_HEADER_INFO_PK_CODE_LIST);
    }

    private transient CodeListPath _codeList;

    /**
     * Get the implicit join path to the <code>code_list</code> table.
     */
    public CodeListPath codeList() {
        if (_codeList == null)
            _codeList = new CodeListPath(this, Keys.HEADER_INFO__FK_HEADER_INFO_PK_CODE_LIST, null);

        return _codeList;
    }

    @Override
    public HeaderInfo as(String alias) {
        return new HeaderInfo(DSL.name(alias), this);
    }

    @Override
    public HeaderInfo as(Name alias) {
        return new HeaderInfo(alias, this);
    }

    @Override
    public HeaderInfo as(Table<?> alias) {
        return new HeaderInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HeaderInfo rename(String name) {
        return new HeaderInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HeaderInfo rename(Name name) {
        return new HeaderInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HeaderInfo rename(Table<?> name) {
        return new HeaderInfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HeaderInfo where(Condition condition) {
        return new HeaderInfo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HeaderInfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HeaderInfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HeaderInfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HeaderInfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HeaderInfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HeaderInfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HeaderInfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HeaderInfo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HeaderInfo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
