/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables;


import com.yupay.amasua.fv3800.model.enums.DoiType;
import com.yupay.amasua.fv3800.model.enums.IndirectType;
import com.yupay.amasua.fv3800.model.jooq.DefaultSchema;
import com.yupay.amasua.fv3800.model.jooq.Keys;
import com.yupay.amasua.fv3800.model.jooq.converters.DoiTypeConverter;
import com.yupay.amasua.fv3800.model.jooq.converters.IndirectTypeConverter;
import com.yupay.amasua.fv3800.model.jooq.converters.UnscaledDecimal6;
import com.yupay.amasua.fv3800.model.jooq.tables.CodeList.CodeListPath;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna.PaykunaPath;
import com.yupay.amasua.fv3800.model.jooq.tables.records.InvolvementRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Involvement extends TableImpl<InvolvementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>involvement</code>
     */
    public static final Involvement INVOLVEMENT = new Involvement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvolvementRecord> getRecordType() {
        return InvolvementRecord.class;
    }

    /**
     * The column <code>involvement.id</code>.
     */
    public final TableField<InvolvementRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>involvement.has_ownership</code>.
     */
    public final TableField<InvolvementRecord, Boolean> HAS_OWNERSHIP = createField(DSL.name("has_ownership"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>involvement.has_control</code>.
     */
    public final TableField<InvolvementRecord, Boolean> HAS_CONTROL = createField(DSL.name("has_control"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>involvement.has_senior_mgmt</code>.
     */
    public final TableField<InvolvementRecord, Boolean> HAS_SENIOR_MGMT = createField(DSL.name("has_senior_mgmt"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>involvement.is_direct</code>.
     */
    public final TableField<InvolvementRecord, Boolean> IS_DIRECT = createField(DSL.name("is_direct"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>involvement.indirect_type</code>.
     */
    public final TableField<InvolvementRecord, IndirectType> INDIRECT_TYPE = createField(DSL.name("indirect_type"), SQLDataType.VARCHAR, this, "", new IndirectTypeConverter());

    /**
     * The column <code>involvement.indirect_relationship</code>.
     */
    public final TableField<InvolvementRecord, Integer> INDIRECT_RELATIONSHIP = createField(DSL.name("indirect_relationship"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>involvement.titular_doi_type</code>.
     */
    public final TableField<InvolvementRecord, DoiType> TITULAR_DOI_TYPE = createField(DSL.name("titular_doi_type"), SQLDataType.VARCHAR, this, "", new DoiTypeConverter());

    /**
     * The column <code>involvement.titular_doi_number</code>.
     */
    public final TableField<InvolvementRecord, String> TITULAR_DOI_NUMBER = createField(DSL.name("titular_doi_number"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>involvement.value_type</code>.
     */
    public final TableField<InvolvementRecord, Integer> VALUE_TYPE = createField(DSL.name("value_type"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>involvement.value_count</code>.
     */
    public final TableField<InvolvementRecord, BigDecimal> VALUE_COUNT = createField(DSL.name("value_count"), SQLDataType.BIGINT.nullable(false), this, "", new UnscaledDecimal6());

    /**
     * The column <code>involvement.value_nominal</code>.
     */
    public final TableField<InvolvementRecord, BigDecimal> VALUE_NOMINAL = createField(DSL.name("value_nominal"), SQLDataType.BIGINT.nullable(false), this, "", new UnscaledDecimal6());

    /**
     * The column <code>involvement.participation_percentage</code>.
     */
    public final TableField<InvolvementRecord, BigDecimal> PARTICIPATION_PERCENTAGE = createField(DSL.name("participation_percentage"), SQLDataType.BIGINT.nullable(false), this, "", new UnscaledDecimal6());

    /**
     * The column <code>involvement.has_voting_rights</code>.
     */
    public final TableField<InvolvementRecord, Boolean> HAS_VOTING_RIGHTS = createField(DSL.name("has_voting_rights"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>involvement.deposit_country</code>.
     */
    public final TableField<InvolvementRecord, Integer> DEPOSIT_COUNTRY = createField(DSL.name("deposit_country"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>involvement.control_description</code>.
     */
    public final TableField<InvolvementRecord, String> CONTROL_DESCRIPTION = createField(DSL.name("control_description"), SQLDataType.CLOB, this, "");

    private Involvement(Name alias, Table<InvolvementRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Involvement(Name alias, Table<InvolvementRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>involvement</code> table reference
     */
    public Involvement(String alias) {
        this(DSL.name(alias), INVOLVEMENT);
    }

    /**
     * Create an aliased <code>involvement</code> table reference
     */
    public Involvement(Name alias) {
        this(alias, INVOLVEMENT);
    }

    /**
     * Create a <code>involvement</code> table reference
     */
    public Involvement() {
        this(DSL.name("involvement"), null);
    }

    public <O extends Record> Involvement(Table<O> path, ForeignKey<O, InvolvementRecord> childPath, InverseForeignKey<O, InvolvementRecord> parentPath) {
        super(path, childPath, parentPath, INVOLVEMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InvolvementPath extends Involvement implements Path<InvolvementRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InvolvementPath(Table<O> path, ForeignKey<O, InvolvementRecord> childPath, InverseForeignKey<O, InvolvementRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InvolvementPath(Name alias, Table<InvolvementRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InvolvementPath as(String alias) {
            return new InvolvementPath(DSL.name(alias), this);
        }

        @Override
        public InvolvementPath as(Name alias) {
            return new InvolvementPath(alias, this);
        }

        @Override
        public InvolvementPath as(Table<?> alias) {
            return new InvolvementPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<InvolvementRecord> getPrimaryKey() {
        return Keys.INVOLVEMENT__PK_INVOLVEMENT;
    }

    @Override
    public List<ForeignKey<InvolvementRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INVOLVEMENT__FK_INVOLVEMENT_PK_CODE_LIST, Keys.INVOLVEMENT__FK_INVOLVEMENT_PK_PAYKUNA);
    }

    private transient CodeListPath _codeList;

    /**
     * Get the implicit join path to the <code>code_list</code> table.
     */
    public CodeListPath codeList() {
        if (_codeList == null)
            _codeList = new CodeListPath(this, Keys.INVOLVEMENT__FK_INVOLVEMENT_PK_CODE_LIST, null);

        return _codeList;
    }

    private transient PaykunaPath _paykuna;

    /**
     * Get the implicit join path to the <code>paykuna</code> table.
     */
    public PaykunaPath paykuna() {
        if (_paykuna == null)
            _paykuna = new PaykunaPath(this, Keys.INVOLVEMENT__FK_INVOLVEMENT_PK_PAYKUNA, null);

        return _paykuna;
    }

    @Override
    public Involvement as(String alias) {
        return new Involvement(DSL.name(alias), this);
    }

    @Override
    public Involvement as(Name alias) {
        return new Involvement(alias, this);
    }

    @Override
    public Involvement as(Table<?> alias) {
        return new Involvement(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Involvement rename(String name) {
        return new Involvement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Involvement rename(Name name) {
        return new Involvement(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Involvement rename(Table<?> name) {
        return new Involvement(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Involvement where(Condition condition) {
        return new Involvement(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Involvement where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Involvement where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Involvement where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Involvement where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Involvement where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Involvement where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Involvement where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Involvement whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Involvement whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
