/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables;


import com.yupay.amasua.fv3800.model.enums.DoiType;
import com.yupay.amasua.fv3800.model.enums.MaritalStatus;
import com.yupay.amasua.fv3800.model.jooq.DefaultSchema;
import com.yupay.amasua.fv3800.model.jooq.Indexes;
import com.yupay.amasua.fv3800.model.jooq.Keys;
import com.yupay.amasua.fv3800.model.jooq.converters.DoiTypeConverter;
import com.yupay.amasua.fv3800.model.jooq.converters.EpochDaysConverter;
import com.yupay.amasua.fv3800.model.jooq.converters.MaritalStatusConverter;
import com.yupay.amasua.fv3800.model.jooq.tables.CodeList.CodeListPath;
import com.yupay.amasua.fv3800.model.jooq.tables.Involvement.InvolvementPath;
import com.yupay.amasua.fv3800.model.jooq.tables.SpouseParty.SpousePartyPath;
import com.yupay.amasua.fv3800.model.jooq.tables.records.PaykunaRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Paykuna extends TableImpl<PaykunaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>paykuna</code>
     */
    public static final Paykuna PAYKUNA = new Paykuna();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaykunaRecord> getRecordType() {
        return PaykunaRecord.class;
    }

    /**
     * The column <code>paykuna.id</code>.
     */
    public final TableField<PaykunaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>paykuna.resident</code>.
     */
    public final TableField<PaykunaRecord, Boolean> RESIDENT = createField(DSL.name("resident"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>paykuna.doi_type</code>.
     */
    public final TableField<PaykunaRecord, DoiType> DOI_TYPE = createField(DSL.name("doi_type"), SQLDataType.VARCHAR.nullable(false), this, "", new DoiTypeConverter());

    /**
     * The column <code>paykuna.doi_number</code>.
     */
    public final TableField<PaykunaRecord, String> DOI_NUMBER = createField(DSL.name("doi_number"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>paykuna.name</code>.
     */
    public final TableField<PaykunaRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>paykuna.country_residence</code>.
     */
    public final TableField<PaykunaRecord, Integer> COUNTRY_RESIDENCE = createField(DSL.name("country_residence"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>paykuna.birthday</code>.
     */
    public final TableField<PaykunaRecord, LocalDate> BIRTHDAY = createField(DSL.name("birthday"), SQLDataType.BIGINT.nullable(false), this, "", new EpochDaysConverter());

    /**
     * The column <code>paykuna.country_nationality</code>.
     */
    public final TableField<PaykunaRecord, Integer> COUNTRY_NATIONALITY = createField(DSL.name("country_nationality"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>paykuna.address</code>.
     */
    public final TableField<PaykunaRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>paykuna.corporate_role</code>.
     */
    public final TableField<PaykunaRecord, Integer> CORPORATE_ROLE = createField(DSL.name("corporate_role"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>paykuna.phone</code>.
     */
    public final TableField<PaykunaRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>paykuna.marital_status</code>.
     */
    public final TableField<PaykunaRecord, MaritalStatus> MARITAL_STATUS = createField(DSL.name("marital_status"), SQLDataType.VARCHAR.nullable(false), this, "", new MaritalStatusConverter());

    /**
     * The column <code>paykuna.notice_date</code>.
     */
    public final TableField<PaykunaRecord, LocalDate> NOTICE_DATE = createField(DSL.name("notice_date"), SQLDataType.BIGINT.nullable(false), this, "", new EpochDaysConverter());

    /**
     * The column <code>paykuna.spouse</code>.
     */
    public final TableField<PaykunaRecord, Integer> SPOUSE = createField(DSL.name("spouse"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>paykuna.is_legal_representative</code>.
     */
    public final TableField<PaykunaRecord, Boolean> IS_LEGAL_REPRESENTATIVE = createField(DSL.name("is_legal_representative"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Paykuna(Name alias, Table<PaykunaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Paykuna(Name alias, Table<PaykunaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>paykuna</code> table reference
     */
    public Paykuna(String alias) {
        this(DSL.name(alias), PAYKUNA);
    }

    /**
     * Create an aliased <code>paykuna</code> table reference
     */
    public Paykuna(Name alias) {
        this(alias, PAYKUNA);
    }

    /**
     * Create a <code>paykuna</code> table reference
     */
    public Paykuna() {
        this(DSL.name("paykuna"), null);
    }

    public <O extends Record> Paykuna(Table<O> path, ForeignKey<O, PaykunaRecord> childPath, InverseForeignKey<O, PaykunaRecord> parentPath) {
        super(path, childPath, parentPath, PAYKUNA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PaykunaPath extends Paykuna implements Path<PaykunaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PaykunaPath(Table<O> path, ForeignKey<O, PaykunaRecord> childPath, InverseForeignKey<O, PaykunaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PaykunaPath(Name alias, Table<PaykunaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PaykunaPath as(String alias) {
            return new PaykunaPath(DSL.name(alias), this);
        }

        @Override
        public PaykunaPath as(Name alias) {
            return new PaykunaPath(alias, this);
        }

        @Override
        public PaykunaPath as(Table<?> alias) {
            return new PaykunaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UX_PAYKUNA_DOI);
    }

    @Override
    public UniqueKey<PaykunaRecord> getPrimaryKey() {
        return Keys.PAYKUNA__PK_PAYKUNA;
    }

    @Override
    public List<ForeignKey<PaykunaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PAYKUNA__FK_PAYKUNA_PK_CODE_LIST, Keys.PAYKUNA__FK_PAYKUNA_PK_SPOUSE_PARTY);
    }

    private transient CodeListPath _codeList;

    /**
     * Get the implicit join path to the <code>code_list</code> table.
     */
    public CodeListPath codeList() {
        if (_codeList == null)
            _codeList = new CodeListPath(this, Keys.PAYKUNA__FK_PAYKUNA_PK_CODE_LIST, null);

        return _codeList;
    }

    private transient SpousePartyPath _spouseParty;

    /**
     * Get the implicit join path to the <code>spouse_party</code> table.
     */
    public SpousePartyPath spouseParty() {
        if (_spouseParty == null)
            _spouseParty = new SpousePartyPath(this, Keys.PAYKUNA__FK_PAYKUNA_PK_SPOUSE_PARTY, null);

        return _spouseParty;
    }

    private transient InvolvementPath _involvement;

    /**
     * Get the implicit to-many join path to the <code>involvement</code> table
     */
    public InvolvementPath involvement() {
        if (_involvement == null)
            _involvement = new InvolvementPath(this, null, Keys.INVOLVEMENT__FK_INVOLVEMENT_PK_PAYKUNA.getInverseKey());

        return _involvement;
    }

    @Override
    public Paykuna as(String alias) {
        return new Paykuna(DSL.name(alias), this);
    }

    @Override
    public Paykuna as(Name alias) {
        return new Paykuna(alias, this);
    }

    @Override
    public Paykuna as(Table<?> alias) {
        return new Paykuna(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Paykuna rename(String name) {
        return new Paykuna(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Paykuna rename(Name name) {
        return new Paykuna(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Paykuna rename(Table<?> name) {
        return new Paykuna(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Paykuna where(Condition condition) {
        return new Paykuna(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Paykuna where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Paykuna where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Paykuna where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Paykuna where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Paykuna where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Paykuna where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Paykuna where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Paykuna whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Paykuna whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
