/*
 * This file is generated by jOOQ.
 */
package com.yupay.amasua.fv3800.model.jooq.tables;


import com.yupay.amasua.fv3800.model.jooq.DefaultSchema;
import com.yupay.amasua.fv3800.model.jooq.Keys;
import com.yupay.amasua.fv3800.model.jooq.converters.EpochDaysConverter;
import com.yupay.amasua.fv3800.model.jooq.tables.Paykuna.PaykunaPath;
import com.yupay.amasua.fv3800.model.jooq.tables.records.SpousePartyRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpouseParty extends TableImpl<SpousePartyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>spouse_party</code>
     */
    public static final SpouseParty SPOUSE_PARTY = new SpouseParty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpousePartyRecord> getRecordType() {
        return SpousePartyRecord.class;
    }

    /**
     * The column <code>spouse_party.id</code>.
     */
    public final TableField<SpousePartyRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>spouse_party.name</code>.
     */
    public final TableField<SpousePartyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>spouse_party.doi_number</code>.
     */
    public final TableField<SpousePartyRecord, String> DOI_NUMBER = createField(DSL.name("doi_number"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>spouse_party.certain_date</code>.
     */
    public final TableField<SpousePartyRecord, LocalDate> CERTAIN_DATE = createField(DSL.name("certain_date"), SQLDataType.BIGINT.nullable(false), this, "", new EpochDaysConverter());

    /**
     * The column <code>spouse_party.certain_document</code>.
     */
    public final TableField<SpousePartyRecord, String> CERTAIN_DOCUMENT = createField(DSL.name("certain_document"), SQLDataType.CLOB.nullable(false), this, "");

    private SpouseParty(Name alias, Table<SpousePartyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SpouseParty(Name alias, Table<SpousePartyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>spouse_party</code> table reference
     */
    public SpouseParty(String alias) {
        this(DSL.name(alias), SPOUSE_PARTY);
    }

    /**
     * Create an aliased <code>spouse_party</code> table reference
     */
    public SpouseParty(Name alias) {
        this(alias, SPOUSE_PARTY);
    }

    /**
     * Create a <code>spouse_party</code> table reference
     */
    public SpouseParty() {
        this(DSL.name("spouse_party"), null);
    }

    public <O extends Record> SpouseParty(Table<O> path, ForeignKey<O, SpousePartyRecord> childPath, InverseForeignKey<O, SpousePartyRecord> parentPath) {
        super(path, childPath, parentPath, SPOUSE_PARTY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SpousePartyPath extends SpouseParty implements Path<SpousePartyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SpousePartyPath(Table<O> path, ForeignKey<O, SpousePartyRecord> childPath, InverseForeignKey<O, SpousePartyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SpousePartyPath(Name alias, Table<SpousePartyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SpousePartyPath as(String alias) {
            return new SpousePartyPath(DSL.name(alias), this);
        }

        @Override
        public SpousePartyPath as(Name alias) {
            return new SpousePartyPath(alias, this);
        }

        @Override
        public SpousePartyPath as(Table<?> alias) {
            return new SpousePartyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SpousePartyRecord> getPrimaryKey() {
        return Keys.SPOUSE_PARTY__PK_SPOUSE_PARTY;
    }

    private transient PaykunaPath _paykuna;

    /**
     * Get the implicit to-many join path to the <code>paykuna</code> table
     */
    public PaykunaPath paykuna() {
        if (_paykuna == null)
            _paykuna = new PaykunaPath(this, null, Keys.PAYKUNA__FK_PAYKUNA_PK_SPOUSE_PARTY.getInverseKey());

        return _paykuna;
    }

    @Override
    public SpouseParty as(String alias) {
        return new SpouseParty(DSL.name(alias), this);
    }

    @Override
    public SpouseParty as(Name alias) {
        return new SpouseParty(alias, this);
    }

    @Override
    public SpouseParty as(Table<?> alias) {
        return new SpouseParty(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpouseParty rename(String name) {
        return new SpouseParty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpouseParty rename(Name name) {
        return new SpouseParty(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpouseParty rename(Table<?> name) {
        return new SpouseParty(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpouseParty where(Condition condition) {
        return new SpouseParty(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpouseParty where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpouseParty where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpouseParty where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpouseParty where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpouseParty where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpouseParty where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpouseParty where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpouseParty whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpouseParty whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
