/**
 * Root package for all JOOQ-related artifacts used by the FV-3800 module.<br/>
 * <br/>
 * This package serves as the <b>stable, human-maintained entry point</b> for
 * JOOQ integration within the model layer. It intentionally coexists with
 * multiple sub-packages that are fully or partially generated by JOOQ
 * code generation.<br/>
 * <br/>
 * The following responsibilities are defined under this package hierarchy:
 * <ul>
 *   <li>{@code model.jooq.converters}: Hand-written {@link org.jooq.Converter}
 *       implementations defining explicit persistence strategies and storage
 *       contracts.</li>
 *   <li>{@code model.jooq.tables}, {@code model.jooq.records},
 *       {@code model.jooq.pojos}: Code generated by JOOQ, representing the
 *       relational schema in a type-safe Java form.</li>
 * </ul>
 * <br/>
 * While JOOQ generates several sub-packages automatically, this root package
 * exists to provide architectural context, documentation, and ownership for
 * the persistence layer as a whole. It is the only package in this hierarchy
 * whose contents and documentation are intended to be edited and maintained
 * manually.<br/>
 * <br/>
 * <b>Design notes:</b><br/>
 * <ul>
 *   <li>Generated sub-packages must be treated as read-only.</li>
 *   <li>All persistence decisions (e.g. enum mappings, date and decimal
 *       strategies) must be expressed explicitly via converters, not inferred
 *       by generated code.</li>
 *   <li>This package intentionally avoids domain logic; it defines how data
 *       is stored and retrieved, not what it means.</li>
 * </ul>
 * <br/>
 * At build and distribution time, all packages under this namespace are
 * unified into the same module or binary artifact, avoiding JPMS split-package
 * issues while preserving a clear separation of responsibilities at the
 * source level.<br/>
 * <br/>
 * This structure follows the InfoYupay Way: generated code is isolated,
 * persistence contracts are explicit, and architectural intent is documented
 * where it can be controlled.
 *
 * @author David Vidal
 * @version 1.0
 */
package com.yupay.amasua.fv3800.model.jooq;

